### ISSUE TITLE
Tinker_IO + JEI = Crash when viewing recipes.

### ISSUE THREAD

**Issue by darkshadow1809** [mezz/JustEnoughItems#1274]
Seems tinker_io in combination with JEI when looking through recipes seems to crash.
Forwarding this for one of my players.

crash report:
https://pastebin.com/qM7N7Hwv

**Comment by mezz** [comment]
Thanks for the report!
This looks like an issue with Tinker IO, it has been reported and fixed in Tinker I/O release 2.6.1: https://github.com/gkbm2013/tinker-IO/issues/70

**Comment by darkshadow1809** [comment]
@mezz Oh I am sorry, apparently I didn't look close enough. I just saw rendering error and JEI + tinker I figured since he crashed in the recipe screen it was your side :x Thanks!

EDIT: after viewing that it was fixed in 2.6.1 I am using 2.6.1 not sure why its still throwing this error o.o
