### ISSUE TITLE
Jei does not work

### ISSUE THREAD

**Issue by juanduan28** [mezz/JustEnoughItems#2501]
hello, I play in 1.16.5. When I am playing individually the mod works correctly, however when I play it on a server alongside the same mods they all have the same issue of recipes not showing up when clicking on an item. I don't know if there will be any solution to this problem but based on what I have searched I have not found anything and I can assume that it must be a bug

![2021-09-27_22 21 42](https://user-images.githubusercontent.com/91562085/135141246-fbfb7226-4acf-41d8-96dd-a9ccbba46806.png)

![2021-09-27_22 20 46](https://user-images.githubusercontent.com/91562085/135141314-88ec2259-b4b6-46c9-b7b9-6d408166b284.png)

In these photos you can see how pressing does not show the corresponding option, and only shows a few that are not the corresponding option.

**Comment by mezz** [comment]
Thanks for the report!
I think I have fixed this recently, please try with `jei-1.16.5-7.7.1.125` and let me know if that fixes the issue for you.

**Comment by p1ut0nium-git** [comment]
I am having the same issue. No errors or log info to provide. 

Also, using the r key to show recipes does not work either.

Using version: jei-1.16.5-7.7.1.126

**Comment by p1ut0nium-git** [comment]
Turns out it was: Cyan Warrior Swords Mod 3.2 - https://www.curseforge.com/minecraft/mc-mods/cyan-warrior-swords-mod

Removing this mod solves the problem. Some kind of weird conflict?

**Comment by CthonicSyzygies** [comment]
We are having this issue on a server with the current version of JEI. Myself and my partner are able to access JEI's full interface, but the third player who joined cannot pull up recipes. Based on the serverlog, it appears to be a conflict with CraftTweaker or Inventory Sorter. The following is generated in the server console when ONLY that player attempts to open a recipe.
[bug report.txt](https://github.com/mezz/JustEnoughItems/files/7919471/bug.report.txt)

Our full modlist is here.

[modlist.txt](https://github.com/mezz/JustEnoughItems/files/7919472/modlist.txt)

The third player is playing on Linux.

**Comment by CthonicSyzygies** [comment]
This corrected itself on reloading the game, but it still happened in the first place!
