### ISSUE TITLE
[Bug]: [1.19.3 Fabric] Mod refuses to open the config menu, even with configured

### ISSUE THREAD

**Issue by Cloudninjakip** [mezz/JustEnoughItems#3127]
### Steps to Reproduce the Bug

Install latest version of jei and configured on 1.19.3 (fabric), and try to open the config.

### Expected Behavior

It should open the config menu as normal

### Actual Behavior

It says to install configured, even though it is already installed

### latest.log

https://gist.github.com/Cloudninjakip/71a897642599e8c27713fd12570093a2

**Comment by KadTheHunter** [comment]
I have the same issue. Added [Configured-Fabric 2.0.2](https://beta.curseforge.com/minecraft/mc-mods/configured-fabric/files/4166864), restarted game, still says to install it.

**Comment by audaki** [comment]
Config is not implemented for Fabric:

![image](https://user-images.githubusercontent.com/1321285/219871357-253221cd-fd3f-4a56-98b7-5980fb63a8ab.png)

The message is wrong in Fabric, it should say "Config GUI is not implemented for Fabric"

**Comment by vico93** [comment]
Tbh, i hope [Cloth Config](https://modrinth.com/mod/cloth-config/) is choosen to be the default config API for the Fabric port. At least mods using that library have an UI more aligned with vanilla and that library seems to integrate well with [Mod Menu](https://modrinth.com/mod/modmenu), that is the de-facto standard for in-game mod management on Fabric/Quilt

**Comment by audaki** [comment]
> Config is not implemented for Fabric:
> 
> ![image](https://user-images.githubusercontent.com/1321285/219871357-253221cd-fd3f-4a56-98b7-5980fb63a8ab.png)
> 
> The message is wrong in Fabric, it should say "Config GUI is not implemented for Fabric"

@mezz

I guess the message is still wrong, and you still get a lot of opened issues for this.

It will probably reduce your support volume a lot if you change the message. :thinking: 

And the code didn’t change yet:

https://github.com/mezz/JustEnoughItems/blob/1.21.x/Fabric/src/main/java/mezz/jei/fabric/platform/ConfigHelper.java#L19

**Comment by mezz** [comment]
Sorry for the delay.

Configured only works with JEI for Minecraft 1.19.3 and higher, and it does not have a 1.19.4 fabric version on curseforge, so I have implemented this for JEI for Fabric on Minecraft 1.20.1, 1.20.4, 1.20.6, and 1.21.

**Comment by audaki** [comment]
Thank you!

**Comment by Neekodesu** [comment]
Thanks <3

**Comment by Henkaeru** [comment]
There's a version of configured for fabric 1.19.4 but the same issue with the Optional.empty() is still present on this version.

Configured 1.19.4 latest version on modrinth:
https://modrinth.com/mod/configured/version/mc1.19.4-v1.3.1

**Comment by audaki** [comment]
@Henkaeru That’s a different Configured
